### PR TITLE
Use --if-exists with import

### PR DESCRIPTION
**Pull request by dpoirier**
To resolve https://github.com/dokku/dokku-postgres/issues/142

### CODE REVIEW

**Comment by josegonzalez** [comment]
Why does this have my name associated with the commit lol.

**Comment by dpoirier** [comment]
I wondered that too!   Git is mysterious sometimes.

**Comment by josegonzalez** [comment]
This change seems pretty reasonable, @fgblomqvist can you verify this is up to snuff

**Comment by fgblomqvist** [comment]
Looks good to me, thanks for the PR!

**Comment by dpoirier** [comment]
I just noticed that not all versions of Postgres support ```pg_restore --if-exists```.    How far back does this plugin support Postgres? 

(9.4 is the first Postgres version with ```pg_restore --if-exists```.)

**Comment by dpoirier** [comment]
What's the next step on this?

**Comment by josegonzalez** [comment]
It gets merged by me and released. I'm busy with work atm, so this may have to wait another few days.

**Comment by dpoirier** [comment]
Any estimate on when this might get merged and released?

**Comment by KernelMadness** [comment]
@josegonzalez any chance this PR gets merged? :)

**Comment by josegonzalez** [comment]
Totally missed this :P

**Comment by josegonzalez** [comment]
Released in 1.4.4

**Pull request merged**
