### PR TITLE
allows shared memory size of docker container to be adjusted

### PR DESCRIPTION
**Pull request by Uepsilon**
sometimes postgres needs more shared memory than the defaulting 64m docker allows. this gives the option to adjust the shared memory size.

regarding tests: we were not able to run them locally etc. so they might need some love.

### CODE REVIEW

**Comment by marckohlbrugge** [comment]
Since this PR hasn't been merged, does anyone have a temporary workaround for increasing the size of a postgres container? My dokku app has become unusable due to the memory limitation.

**Comment by Alir3z4** [comment]
Wish this could get merged. Very useful. I want to use dokku but the memory limit is a blocker.

**Comment by Uepsilon** [comment]
> Could we reuse the `--memory` flag instead?

this would indeed be clever. I'll change it so it might get merged afterwards :)

**Comment by josegonzalez** [comment]
Actually I changed my mind. `shm-size` is good. Let me take a closer look at this pr for merge :)

**Comment by josegonzalez** [comment]
Hmmm there are some conflicts and it doesn't seem like I can modify the upstream MR. I'll work on this locally and merge it in. Thanks for the initial effort here :)

**Pull request closed without merging**
