### PR TITLE
Fix the `destroy` command

### PR DESCRIPTION
**Pull request by Flink**
Checking for container with its service name instead of ID.
Doing a chmod 777 on `/data` before removing data from the service.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Should this be ported everywhere? In a similar vein, did you port the link/unlink logic to every plugin?

**Comment by Flink** [comment]
Yes I think this should be ported everywhere. For the link/unlink I’m on it (only 4 more plugins ;))

**Comment by josegonzalez** [comment]
I'll merge when those are done ;)

**Comment by Flink** [comment]
ok :stuck_out_tongue_winking_eye:

**Pull request merged**
