### PR TITLE
Creation of custom user for postgres plugin

### PR DESCRIPTION
**Pull request by sebastiken**
It modifies create command to create a postgresql user that is the owner of the database to be created.

### CODE REVIEW

**Comment by Flink** [comment]
Thanks for your contribution!
I was wondering though if this wasn’t a little out of scope of this plugin? If somebody wants to create an extra user, he can do so by issuing the correct commands.

Thoughts? @josegonzalez @sebastiken

**Comment by josegonzalez** [comment]
I think it's out of the scope. Maybe we should instead expose the root login info and note in the readme the permissions of the user that is auto-created.

**Comment by sebastiken** [comment]
@josegonzalez we have talk about this modification at IRC channel. You tell me that I could check *mongodb* plugin which creates a custom user, too.
I made the same modification in this plugin. Please, tell me what modifications you think are correct.
Maybe a new plugin command to create new user?
Thanks

**Comment by josegonzalez** [comment]
Doesnt the original postgres user have access to this db, as specified [here](https://github.com/dokku/dokku-postgres/pull/44/files#diff-5f6bc08c46cee6f21bfcdd08aff6e8aaR40)?

**Comment by sebastiken** [comment]
@josegonzalez it has access. But the app that I am using doesn't allow to connect to Postgres DB using *postgres* user. So, I create the custom user. We have talk about this in #dokku IRC Channel.

**Comment by josegonzalez** [comment]
@Flink thoughts on this? I think we can do something like:

```shell
# by default, simply create a `postgres` user on a database
dokku postgres:create <db>

# we store the user/pass info in a set of files
# located in
#
#     /var/lib/dokku/services/postgres/SERVICE/auth/username
#
# where the username is the name of the user, 
# and the contents are the password. Note that we
# will need to migrate all the old auth stuff over, including
# any root users.

# create a custom user
dokku postgres:create-user <db> <user> <pass>

# linking uses the postgres user by default
dokku postgres:link <db> <app>

# you can specify the user to use when linking
dokku postgres:link <db> <app> <user>
```

**Comment by Flink** [comment]
@josegonzalez I’m not sure about this, I think we’ll be really complicating things if we’re going down this road.
If we want, we could use the `POSTGRES_USER` variable when creating the service to use another user than postgres (might be better by the way).
Then the DB is available, can be exposed and so managed easily with frontends, the user is an admin one, so anyone can do anything in their DB. I just fear that if we begin to manage users and other databases, then what will be next? I don’t know, just saying :)

**Comment by Flink** [comment]
I see there’s indeed a need for a single container approach (https://github.com/Flink/dokku-psql-single-container/issues/19). So after giving it some thoughts, maybe we could do something like you describe @josegonzalez. I don’t know if we need to create users and databases separately or if generating a user per database is enough. We also need those `--user` and `--database` options everywhere (`connect`, `export`, `import`, etc.). I’ll try to code something :)

**Comment by sebastiken** [comment]
@Flink @josegonzalez maybe this PR is useless now. The approach of @josegonzalez seems to be more useful, but I agree with @Flink that it could complicate other *postgres plugin commands*.

**Comment by danielrhodes** [comment]
I'm also very interested in this. The memory overhead of multiple running postgres instances is rather high when postgres already supports the security features required to sandbox individual databases. Running multiple docker instances in this case is really just fitting a square peg in a round hole.

**Comment by josegonzalez** [comment]
I'm going to close this PR as it is unlikely to be merged as is and the ui it exposes is not the end goal.

**Pull request closed without merging**
