### PR TITLE
add a --use-iam flag to backup

### PR DESCRIPTION
**Pull request by dustMason**
When dokku runs on an EC2 node, it is not necessary to provide and store credentials. They are available via the EC2 metadata service automatically.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Docker daemons do not have access to the metadata api by default, so this technically won't work.

Also, shellcheck is failing now, though thats easy enough to fix.

**Comment by dustMason** [comment]
@josegonzalez To test this out, I created a new EC2 running Ubuntu 16.04, installed current dokku, installed my forked plugin and it worked!

This may have been a recent change. See http://stackoverflow.com/questions/35495028/docker-containers-seem-to-inherit-the-instance-profile-of-the-host-ec2-how

I will fix the shellcheck errors

**Comment by dustMason** [comment]
@josegonzalez let me know if i can further help resolve this. if you'd like to see it working with your own eyes, try `curl http://169.254.169.254/latest/meta-data/iam/security-credentials/myrole` from within a docker container on a fresh EC2 node (as described in SO answer below).

http://stackoverflow.com/questions/22409367/fetching-aws-instance-metadata-from-within-docker-container/22411611#22411611

**Comment by dustMason** [comment]
@josegonzalez sorry to pester you about this. any chance you can look at this soon? thanks

**Comment by dustMason** [comment]
@josegonzalez you can confirm that this works with the followings steps:

1. Create a new EC2 instance with Ubuntu 16.04 AMI and SSH in
2. `sudo apt install docker.io`
3. `sudo docker run tutum/curl`
4. `sudo docker run -t tutum/curl bash`
5. `curl http://169.254.169.254/latest/meta-data/iam/info`

```
{
  "Code" : "Success",
  "LastUpdated" : "2017-05-30T18:00:19Z",
  "InstanceProfileArn" : "arn:aws:iam::789201682619:instance-profile/xxx",
  "InstanceProfileId" : "XXX"
}
```

This makes sense because requests to the metadata API are outgoing, which appear not to blocked by default.

**Comment by josegonzalez** [comment]
Will take me a bit, have to setup my AWS account again :)

**Comment by dustMason** [comment]
Hi @josegonzalez, were you ever able to test this?

**Comment by josegonzalez** [comment]
Merged and implemented everywhere.

**Pull request merged**
