### PR TITLE
Updating postgres version to 13

### PR DESCRIPTION
**Pull request by awbdallas**

### CODE REVIEW

**Comment by josegonzalez** [comment]
Weird why didn't tests run...

**Comment by kudapara** [comment]
Is this project still being actively maintained?
Why are we still stuck on version 11?
Is there a technical reason behind that decision or making it default to the new version 13 will cause some backwards incompatibility changes?

**Comment by josegonzalez** [comment]
I forgot about the PR, thats why.

I'll have a bit of time this weekend to devote to the Dokku plugins, and will try and get to this. If you'd like to bribe me into fixing it, feel free to sponsor the Dokku project. Proceeds go directly to snacks I'll be eating while updating plugins.

**Comment by CleitonDeLima** [comment]
When updating do you need to do some type of restoration in DB?

**Comment by josegonzalez** [comment]
Closing as part of #236.

**Pull request closed without merging**
