### PR TITLE
Update PostgreSQL to v9.6.0

### PR DESCRIPTION
**Pull request by sonicdoe**

### CODE REVIEW

**Comment by josegonzalez** [comment]
Have you verified that this works locally?

**Comment by SonicHedgehog** [comment]
Yes, I have tested a few SQL statements with a fresh installation of Dokku on DigitalOcean.

**Comment by deepj** [comment]
Hello, is it possible to upgrade to PG 9.6.1 and merge this PR, please?

**Comment by sonicdoe** [comment]
@josegonzalez If you’d like, I can update PostgreSQL to v9.6.1, verify that it works, and open another pull request.

**Comment by josegonzalez** [comment]
Sure.

**Pull request merged**
